image:
  file: .gitpod.Dockerfile
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser

tasks:
  - name: DB Server
    command: curl ${SETUP_URL} | sudo bash 
    openMode: split-right
  

